name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: true
      - name: Set up examples
        run: |-
          git clone https://github.com/apple-oss-distributions/objc4 examples/objc4 --single-branch --depth=1 --filter=blob:none
          git clone https://github.com/llvm-mirror/clang examples/clang --single-branch --depth=1 --filter=blob:none
          git clone https://github.com/HandBrake/HandBrake examples/HandBrake --single-branch --depth=1 --filter=blob:none
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |
            examples/**/*.m
            !examples/HandBrake/macosx/HBController.m
            !examples/HandBrake/macosx/HBCore.m
            !examples/HandBrake/macosx/HBFilters.m
            !examples/HandBrake/macosx/HBImageUtilities.m
            !examples/HandBrake/macosx/HBJob.m
            !examples/HandBrake/macosx/HBPresetsManager.m
            !examples/HandBrake/macosx/HBRedirect.m
            !examples/HandBrake/macosx/HBUtilities.m
            !examples/clang/test/ARCMT/GC-check.m
            !examples/clang/test/ARCMT/nonobjc-to-objc-cast.m
            !examples/clang/test/ARCMT/objcmt-arc-cf-annotations.m
            !examples/clang/test/ARCMT/objcmt-atomic-property.m
            !examples/clang/test/ARCMT/objcmt-migrate-all.m
            !examples/clang/test/ARCMT/objcmt-ns-enum-crash.m
            !examples/clang/test/ARCMT/objcmt-ns-macros.m
            !examples/clang/test/ARCMT/objcmt-ns-nonatomic-iosonly.m
            !examples/clang/test/ARCMT/objcmt-ns-returns-inner-pointer.m
            !examples/clang/test/ARCMT/objcmt-property.m
            !examples/clang/test/ARCMT/objcmt-subscripting-literals.m
            !examples/clang/test/AST/property-atomic-bool.m
            !examples/clang/test/Analysis/Checkers/RunLoopAutoreleaseLeakChecker.m
            !examples/clang/test/Analysis/misc-ps.m
            !examples/clang/test/Analysis/retain-release-arc.m
            !examples/clang/test/Analysis/retain-release.m
            !examples/clang/test/Analysis/vector.m
            !examples/clang/test/CodeCompletion/objc-protocol-member-access.m
            !examples/clang/test/CodeCompletion/pch-and-module.m
            !examples/clang/test/CodeGen/sanitize-thread-no-checking-at-run-time.m
            !examples/clang/test/CodeGenObjC/arc-blocks.m
            !examples/clang/test/CodeGenObjC/arc-precise-lifetime.m
            !examples/clang/test/CodeGenObjC/externally-retained.m
            !examples/clang/test/CodeGenObjC/objc-container-subscripting.m
            !examples/clang/test/CodeGenObjC/objc-fixed-enum.m
            !examples/clang/test/CodeGenObjC/objc-gc-aggr-assign.m
            !examples/clang/test/FixIt/fixit-autoreleasepool.m
            !examples/clang/test/FixIt/fixit-objc-message.m
            !examples/clang/test/FixIt/fixit-objc.m
            !examples/clang/test/FixIt/fixit-static-object-decl.m
            !examples/clang/test/FixIt/typo.m
            !examples/clang/test/Frontend/noderef_on_non_pointers.m
            !examples/clang/test/Index/Core/external-source-symbol-attr.m
            !examples/clang/test/Index/Core/index-source.m
            !examples/clang/test/Index/annotate-comments-objc.m
            !examples/clang/test/Index/cindex-on-invalid-usrs.m
            !examples/clang/test/Index/cindex-on-invalid.m
            !examples/clang/test/Index/complete-block-property-assignment.m
            !examples/clang/test/Index/complete-in-invalid-method.m
            !examples/clang/test/Index/complete-method-decls.m
            !examples/clang/test/Index/complete-objc-message-id.m
            !examples/clang/test/Index/complete-objc-message.m
            !examples/clang/test/Index/complete-parameterized-classes.m
            !examples/clang/test/Index/complete-preprocessor.m
            !examples/clang/test/Index/complete-protocols.m
            !examples/clang/test/Index/complete-super.m
            !examples/clang/test/Index/get-cursor.m
            !examples/clang/test/Index/index-attrs.m
            !examples/clang/test/Index/index-decls.m
            !examples/clang/test/Index/index-invalid-code.m
            !examples/clang/test/Index/invalid-code-rdar10451854.m
            !examples/clang/test/Index/pch-with-errors.m
            !examples/clang/test/Index/unmatched-braces.m
            !examples/clang/test/Lexer/minimize_source_to_dependency_directives_at_import_extra_tokens.m
            !examples/clang/test/Lexer/minimize_source_to_dependency_directives_at_import_missing_semi.m
            !examples/clang/test/Modules/objc-at-keyword.m
            !examples/clang/test/Modules/redefinition-c-tagtypes.m
            !examples/clang/test/Parser/attr-external-source-symbol.m
            !examples/clang/test/Parser/c2x-attributes.m
            !examples/clang/test/Parser/check-syntax-1.m
            !examples/clang/test/Parser/debugger-import-module.m
            !examples/clang/test/Parser/method-def-in-class.m
            !examples/clang/test/Parser/method-prototype-1.m
            !examples/clang/test/Parser/missing-closing-rbrace.m
            !examples/clang/test/Parser/missing-end-2.m
            !examples/clang/test/Parser/missing-end-3.m
            !examples/clang/test/Parser/missing-end-4.m
            !examples/clang/test/Parser/missing-end.m
            !examples/clang/test/Parser/objc-at-directive-fixit.m
            !examples/clang/test/Parser/objc-at-implementation-eof-crash.m
            !examples/clang/test/Parser/objc-at-interface-eof-crash.m
            !examples/clang/test/Parser/objc-available.m
            !examples/clang/test/Parser/objc-boxing.m
            !examples/clang/test/Parser/objc-error-qualified-implementation.m
            !examples/clang/test/Parser/objc-forcollection-neg-2.m
            !examples/clang/test/Parser/objc-foreach-syntax.m
            !examples/clang/test/Parser/objc-implementation-attrs.m
            !examples/clang/test/Parser/objc-init.m
            !examples/clang/test/Parser/objc-interfaces.m
            !examples/clang/test/Parser/objc-messaging-1.m
            !examples/clang/test/Parser/objc-messaging-neg-1.m
            !examples/clang/test/Parser/objc-missing-impl.m
            !examples/clang/test/Parser/objc-property-syntax.m
            !examples/clang/test/Parser/objc-quirks.m
            !examples/clang/test/Parser/objc-static-assert.m
            !examples/clang/test/Parser/objc-synthesized-recover.m
            !examples/clang/test/Parser/objc-try-catch-1.m
            !examples/clang/test/Parser/objcbridge-related-attribute.m
            !examples/clang/test/Parser/placeholder-recovery.m
            !examples/clang/test/Parser/recovery.m
            !examples/clang/test/Sema/attr-objc-bridge-related.m
            !examples/clang/test/SemaObjC/arc-bridged-cast.m
            !examples/clang/test/SemaObjC/arc-cf.m
            !examples/clang/test/SemaObjC/arc-non-pod-memaccess.m
            !examples/clang/test/SemaObjC/attr-deprecated-replacement-fixit.m
            !examples/clang/test/SemaObjC/attr-designated-init.m
            !examples/clang/test/SemaObjC/attr-objc-gc.m
            !examples/clang/test/SemaObjC/class-unavail-warning.m
            !examples/clang/test/SemaObjC/crash-label.m
            !examples/clang/test/SemaObjC/crash-on-objc-bool-literal.m
            !examples/clang/test/SemaObjC/crash-on-type-args-protocols.m
            !examples/clang/test/SemaObjC/delay-parsing-cfunctions.m
            !examples/clang/test/SemaObjC/diagnose_if.m
            !examples/clang/test/SemaObjC/enum-fixed-type.m
            !examples/clang/test/SemaObjC/externally-retained.m
            !examples/clang/test/SemaObjC/foreach.m
            !examples/clang/test/SemaObjC/incomplete-implementation.m
            !examples/clang/test/SemaObjC/interface-1.m
            !examples/clang/test/SemaObjC/invalid-code.m
            !examples/clang/test/SemaObjC/method-bad-param.m
            !examples/clang/test/SemaObjC/method-def-1.m
            !examples/clang/test/SemaObjC/method-no-context.m
            !examples/clang/test/SemaObjC/method-sentinel-attr.m
            !examples/clang/test/SemaObjC/mismatched-undefined-method.m
            !examples/clang/test/SemaObjC/missing-atend-metadata.m
            !examples/clang/test/SemaObjC/nonnull.m
            !examples/clang/test/SemaObjC/objc-asm-attribute-neg-test.m
            !examples/clang/test/SemaObjC/objc-boxed-expressions-nsvalue.m
            !examples/clang/test/SemaObjC/objc-cf-audited-warning.m
            !examples/clang/test/SemaObjC/parameterized_classes.m
            !examples/clang/test/SemaObjC/property-9.m
            !examples/clang/test/SemaObjC/property.m
            !examples/clang/test/SemaObjC/protocol-archane.m
            !examples/clang/test/SemaObjC/protocols.m
            !examples/clang/test/SemaObjC/self-assign.m
            !examples/clang/test/SemaObjC/severe-syntax-error.m
            !examples/clang/test/SemaObjC/sizeof-interface.m
            !examples/clang/test/SemaObjC/string.m
            !examples/clang/test/SemaObjC/strong-in-c-struct.m
            !examples/clang/test/SemaObjC/transfer-boxed-string-nullability.m
            !examples/clang/test/SemaObjC/unguarded-availability-new.m
            !examples/clang/test/SemaObjC/unguarded-availability.m
            !examples/clang/test/SemaObjC/x86-method-vector-values.m
            !examples/objc4/test/02-concurrentcat.m
            !examples/objc4/test/04-load-image-notification.m
            !examples/objc4/test/05-load-image-notification2.m
            !examples/objc4/test/MRCBase.m
            !examples/objc4/test/accessors.m
            !examples/objc4/test/arr-cast.m
            !examples/objc4/test/badCache.m
            !examples/objc4/test/badSuperclass.m
            !examples/objc4/test/blocksAsImps.m
            !examples/objc4/test/category.m
            !examples/objc4/test/customrr-nsobject.m
            !examples/objc4/test/evil-class-def.m
            !examples/objc4/test/exc.m
            !examples/objc4/test/fakeRealizedClass.m
            !examples/objc4/test/fakeRealizedClass2.m
            !examples/objc4/test/foreach.m
            !examples/objc4/test/forward.m
            !examples/objc4/test/initialize.m
            !examples/objc4/test/ivarSlide.m
            !examples/objc4/test/literals.m
            !examples/objc4/test/load-map-images.m
            !examples/objc4/test/load-parallel0.m
            !examples/objc4/test/msgSend-performance.m
            !examples/objc4/test/msgSend.m
            !examples/objc4/test/nsobject.m
            !examples/objc4/test/protocolSmall.m
            !examples/objc4/test/restartableRangesSynchronizeStress.m
            !examples/objc4/test/retain-release-helpers.m
            !examples/objc4/test/rr-autorelease-fast.m
            !examples/objc4/test/rr-autorelease-fastarc.m
            !examples/objc4/test/subscripting.m
            !examples/objc4/test/swift-class-def.m
            !examples/objc4/test/swiftMetadataInitializerRealloc-dylib1.m
            !examples/objc4/test/swiftMetadataInitializerRealloc.m
            !examples/objc4/test/swiftStubClassList.m
            !examples/objc4/test/taggedNSPointers.m
            !examples/objc4/test/taggedPointers.m
            !examples/objc4/test/unwind.m
            !examples/objc4/test/weakcopy.m
